#!/usr/bin/env bash
#
# gen-dev-keys.sh - generates the development RSA key pair and demo credentials.
#
# Produces .env.dev-keys, which docker compose loads to start the system without
# any manual editing. The file is gitignored and is a DEVELOPMENT artefact: the
# keys are written with a passphrase-free RSA key, because a container has
# nowhere to prompt for one.
#
# For anything beyond a local run, generate the keys in a secret manager and
# inject them through the platform's secret mechanism instead. See docs/adr.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT="${REPO_ROOT}/.env.dev-keys"

KEY_SIZE=2048
DEMO_USERNAME="${DEMO_USERNAME:-demo}"
DEMO_PASSWORD="${DEMO_PASSWORD:-demo-password}"

log() { printf '%s\n' "$*" >&2; }
die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

command -v openssl >/dev/null 2>&1 || die "openssl is required but was not found in PATH"

if [[ -f "${OUTPUT}" ]]; then
  log "refusing to overwrite ${OUTPUT}"
  log "delete it first if you really want new keys"
  exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

log "generating a ${KEY_SIZE}-bit RSA key pair"
openssl genpkey \
  -algorithm RSA \
  -pkeyopt rsa_keygen_bits:"${KEY_SIZE}" \
  -out "${WORK_DIR}/private.pem" 2>/dev/null

# The public key must be derived from the private one, never generated
# independently: two independently generated keys would simply not match.
openssl pkey \
  -in "${WORK_DIR}/private.pem" \
  -pubout \
  -out "${WORK_DIR}/public.pem" 2>/dev/null

log "hashing the demo password with argon2id"
# The hash is produced through Node because argon2 is a native module: shelling
# out to a separate argon2 CLI would add a dependency the project does not have.
#
# argon2 is installed here on demand. The documented quick start is
# `cp .env.example .env && ./scripts/gen-dev-keys.sh && docker compose up`, and
# asking the developer to remember an extra `npm ci` between the two steps is
# how a quick start stops being a quick start. The password is passed through
# the environment rather than on the command line, so it never appears in the
# process table.
cd "${REPO_ROOT}/services/auth-service"

if ! node -e 'require.resolve("argon2")' >/dev/null 2>&1; then
  log "argon2 is not installed; installing dependencies for auth-service"
  command -v npm >/dev/null 2>&1 || die "npm is required to install argon2 but was not found in PATH"
  npm ci --silent
fi

NODE_HASH="$(DEMO_PASSWORD="${DEMO_PASSWORD}" node -e '
const argon2 = require("argon2");
const password = process.env.DEMO_PASSWORD;
if (!password) {
  process.stderr.write("DEMO_PASSWORD is not set\n");
  process.exit(1);
}
argon2
  .hash(password, {
    type: argon2.argon2id,
    memoryCost: 19456,
    timeCost: 2,
    parallelism: 1,
  })
  .then((hash) => process.stdout.write(hash))
  .catch((error) => {
    process.stderr.write(`${error.message}\n`);
    process.exit(1);
  });
')" || die "failed to hash the demo password"

[[ -n "${NODE_HASH}" ]] || die "argon2 produced an empty hash"

# .env files are read by docker compose and by Node's dotenv-style loaders,
# which do not expand variables inside values. The PEM is therefore emitted with
# literal \n sequences, which the service converts back to real newlines at
# startup.
escape_pem() {
  # shellcheck disable=SC2016
  sed -e ':a' -e '$!{N;ba' -e '}' -e 's/%/\\%/g' -e 's/\r//' -e 's/\n/\\n/g' "$1"
}

PRIVATE_ESCAPED="$(escape_pem "${WORK_DIR}/private.pem")"
PUBLIC_ESCAPED="$(escape_pem "${WORK_DIR}/public.pem")"

# Compose performs ${...} interpolation on env_file values as well as on the
# `environment:` block, and an argon2id PHC string is full of `$` characters
# ($argon2id$v=19$m=...). Left alone they are silently replaced by empty strings
# and the service then refuses to start with "must be an argon2id hash", which
# points nowhere near the real cause. Compose collapses a literal `$$` back to
# `$`, so every dollar sign is doubled here.
escape_dollars() {
  # shellcheck disable=SC2016
  printf '%s' "$1" | sed 's/\$/$$/g'
}

HASH_ESCAPED="$(escape_dollars "${NODE_HASH}")"

cat >"${OUTPUT}" <<EOF
# ---------------------------------------------------------------------------
# Generated by scripts/gen-dev-keys.sh - DEVELOPMENT CREDENTIALS, DO NOT COMMIT.
# Regenerate by deleting this file and re-running the script.
# ---------------------------------------------------------------------------

JWT_PRIVATE_KEY_PEM=${PRIVATE_ESCAPED}
JWT_PUBLIC_KEY_PEM=${PUBLIC_ESCAPED}
JWT_KID=dev-key-$(date +%Y%m%d%H%M%S)

DEMO_USERNAME=${DEMO_USERNAME}
DEMO_PASSWORD=${DEMO_PASSWORD}
DEMO_PASSWORD_HASH=${HASH_ESCAPED}
EOF

chmod 600 "${OUTPUT}"

log "wrote ${OUTPUT}"
log ""
log "demo credentials:  ${DEMO_USERNAME} / ${DEMO_PASSWORD}"
log ""
log "The compose file reads that file directly through env_file, and mounts it"
log "into auth-service only. Dollar signs in it are doubled, because Compose"
log "interpolates env_file values too."
log ""
log "next:"
log "  docker compose up --build"
